# encoding: UTF-8

require './buri.rb'

desc 'default'
task :default do
  puts '嗨，我是行俠仗義的不理不理左衛門，執行 `$ rake tasks` 看看我能做些什麼吧！'
end

desc 'task list'
task :tasks do
  puts "`$ rake install` 將會招喚 #{install_list} 等程式, 並不會更改任何設定檔。"
end

def install_list
  'curl asdf git zsh imagemagick neovim tmux vim-plug font-hack-nerd-font oh-my-zsh'
end

desc 'Build developer environment'
task :help_me_to_develop do
  Rake::Task['install'].invoke
  Rake::Task['setup'].invoke
end

desc 'Install'
task :install do
  buri "
  準備安裝一些東西囉！我將會招喚 #{install_list} 到你的電腦裡面啦！"

  brew_install_list = {
    curl: 'curl',
    asdf: 'asdf',
    git: 'git',
    zsh: 'zsh',
    imagemagick: 'convert',
    neovim: 'nvim',
    tmux: 'tmux'
  }
  brew_install_apps(brew_install_list)

  install_vim_plug
  install_font_hack_nerd_font
  # install_oh_my_zsh
  success 'Install done.'
end

desc 'Setup'
task :setup do
  info 'Set shell to zsh'
  execute 'chsh -s /bin/zsh'
  import_iterm2_profile
  backup_and_replace_zsh
end

private

def installed?(app)
  system "which #{app}"
end

def brew_install_apps(apps)
  install_list = %w()
  uninstalled = %w()
  apps.each do |app_name, plugin_name|
    if installed?(plugin_name)
      installed << app_name
    else
      uninstalled << app_name
    end
  end
  info "Plugins are installed by brew: #{installed.join(' ')}"
  if uninstalled.empty?
    info "There is no more plugins need to be installed by brew."
  else
    info "Try install plugings by brew: #{uninstalled.join(' ')}"
    execute "brew install #{uninstalled.join(' ')}"
  end
end

def install_vim_plug
  # nvim 可以快速安裝 plugn
  unless File.exist?("#{Dir.home}/.local/share/nvim/site/autoload/plug.vim")
    execute "sh -c 'curl -fLo \"${XDG_DATA_HOME:-$HOME/.local/share}\"/nvim/site/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'" if mac_os?
    execute "curl -fLo ~/.var/app/io.neovim.nvim/data/nvim/site/autoload/plug.vim \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" if linux?
  end
end

def install_font_hack_nerd_font
  # This is one of font-hack-nerd-font file.
  if File.exist?("#{Dir.home}/Library/Fonts/Hack Italic Nerd Font Complete.ttf")
    info 'font-hack-nerd-font aleady installed.'
  else
    execute 'brew tap homebrew/cask-fonts'
    execute 'brew cask install font-hack-nerd-font'
  end
end

def install_oh_my_zsh
  execute 'sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"' unless File.exist?("#{Dir.home}/.oh-my-zsh")
end

def import_iterm2_profile
  # Manual import json now
end

def backup_and_replace_zsh
  info 'Backup oringin .zshrc'
  execute 'cp ~/.zshrc ./backup/.zshrc'
  info 'Import new .zshrc'
  execute 'cp ./.zshrc ~/.zshrc'
end
